language: c
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC
    - DEVKITARM=${DEVKITPRO}/devkitARM

cache:
  directories:
    - ${DEVKITPRO}

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${DEVKITPRO}"
  - wget https://downloads.devkitpro.org/devkitPPC_r29-1-x86_64-linux.tar.bz2 -O devkitPPC-linux.tar.bz2
  - wget https://downloads.devkitpro.org/devkitARM_r47-x86_64-linux.tar.bz2 -O devkitARM-linux.tar.bz2
  - wget https://github.com/Maschell/dynamic_libs/archive/lib.tar.gz -O dynamic_libs.tar.gz
  - wget https://github.com/Maschell/libutils/archive/master.tar.gz -O libutils.tar.gz
  - wget https://github.com/aliaspider/libfat/archive/master.tar.gz -O libfat.tar.gz
  - wget https://github.com/dimok789/libiosuhax/archive/master.tar.gz -O libiosuhax.tar.gz
  - wget https://github.com/Maschell/libntfs-wiiu/archive/master.tar.gz -O libntfs.tar.gz
  - wget https://github.com/Maschell/fs_wrapper/archive/master.tar.gz -O fs_wrapper.tar.gz

install:
  - tar -xjf devkitPPC-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xjf devkitARM-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xzvf dynamic_libs.tar.gz
  - tar -xzvf libutils.tar.gz
  - tar -xzvf libfat.tar.gz
  - tar -xzvf libiosuhax.tar.gz
  - tar -xzvf libntfs.tar.gz
  - tar -xzvf fs_wrapper.tar.gz
  - 7z x -y ./dynamic_libs-lib/libs/portlibs.zip -o${DEVKITPRO}
  - (cd libiosuhax-master && make -j8 && make install)
  - (cd libfat-master && make wiiu-release && make wiiu-install)
  - (cd libntfs-wiiu-master && make wiiu-install)
  - (cd dynamic_libs-lib && make -j8 && make install)
  - (cd libutils-master && make -j8 && make install)
  - (cd fs_wrapper-master && make -j8 && make install)

script:
- make

before_deploy:
- mkdir -p "wiiu/apps/sdcafiine"
- commit="$(git rev-parse --short=7 HEAD)"
- chmod +x gitrev.sh
- versiontag="$(./gitrev.sh)"
- make
- cp meta/* wiiu/apps/sdcafiine
- cp sdcafiine.elf wiiu/apps/sdcafiine
- zip -r sdcafiine_$versiontag.zip wiiu
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=SDCafiine-$versiontag
- commitLog="$(git log -1 --pretty=%B)"
- commitMessage="$(echo -e "-\n" && echo "SDCafiine nightly build. Not a stable release. Expect bugs!" && echo -e "\nCommitlog:\n")"
- git tag $GIT_TAG -a -m "$commitMessage" -m "$commitLog"
- git push --quiet https://$GITHUBKEY@github.com/Maschell/SDCafiine $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key:
    secure: "if6/uEF7XcfbNk/32Jtbr/FPObciLUPCm9mmw3Ca7RAYKsqEHr1tWM46zaMQMCJNb6W2AXtNx8rllqre8LVpPQLVCgwG+6k0y5DzLPHc+ya1tuj2sPBBvA34OTwPc+ujozhOIWjpu4vS9W+6x5NEvtRgF2jEdST2/jU4nvv4wsNlaBQiAikSh2Vfgxtu9CxeHf/1aXFhfbhoT9at2p070zoYMIbVU+3ystukREs4EixVjTQQcBRSmwNb0HJ4hBtjTR+66T/nZ6jbdWLhhu70cnnjMXs3tC7Dbrrnwy3X0Rsg7m3BMJxqmt/jIiaA0MwEd/86gNrf0H60whTgrIIKWyucrLblB0gm6WV6W5/Guh0pZ3+lPBtbLP5zWUeZFkdgex0fnGH3qdPfyq+DLih+JJgroGTsXTBQ2I0CSd6DWs+hDAF1pebqbBa/KxBBYR3gTEbd8eUFlhol1jILtffYSl8SgCF4Nvsy6hVdaW4yXw/aZAgiYzM0O7VJUiWm3hujvLBHIaZiT1xcJ+Cq280bgyna8AByuRE4Pfewfo1xUlTMDMUVmFOHsUmo1IR/5EXRji3kAVfyyfB5viurxujBCBWXYodquGJ2hExtLurVq7OaJ/RReXzHUORUEgdUFXIYtXKezZ7wfYHf0Ah55Rk1saBQcBHknnrqE8mSEsgOuiw="
  file: sdcafiine_$versiontag.zip
  on:
    repo: Maschell/SDCafiine
    tags: false
    all_branches: true